baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Portfolio'
theme = 'awesome-identity'

## Profile Configurations
[params.profile]
  portrait = "/images/javier.jpg"
  firstname = "Javier"
  lastname = "Castillo"
  title = "DEV OPS ENGiNEER · AWS · PROGRAM MANAGEMENT"
  bio = """Current E-Learning and Digital Platforms Officer at CVC. Former Lead Web Developer at the Vice-presidency Office of the Dominican Republic and former IT Intern at Asociación Cibao Bank. 

Avid learner and proactive problem solver. Castillo often takes on responsibilities of every IT role which has provided a wide variety of skills. Working on a team, alone or under time constraints, any challenge is welcomed with open arms.

Castillo holds a Bachelor of Engineering for Software Engineering from Pontificia Universidad Católica Madre & Maestra (PUCMM) and an Associate's Degree in Computer Science from Tompkins Cortland Community College.
  """

## Contacts Configurations
[params.contacts]
  email = "javiercastillo2708@gmail.com"
  github = "vanorix"
  linkedin = "jcastilloram"
  instagram = "vanorix"

## Footer Configurations
[params.footer]
  copyright = "© 2023 Javier Castillo."
  poweredBy = false